FROM node:22 AS frontend-builder
ARG USE_OLLAMA

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .


ENV NEXT_PUBLIC_BACKEND_URI=""
ENV NEXT_PUBLIC_USE_OLLAMA=$USE_OLLAMA

RUN yarn build

FROM nginx:1.15

RUN rm -rf /usr/share/nginx/html/*

COPY --from=frontend-builder /app/out /usr/share/nginx/html

RUN chmod -R 755 /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]